### ISSUE TITLE
couple of easy to fix bugs

### ISSUE THREAD

**Issue by jesuistay** [hirofumi0810/asr_preprocessing#2]
(1) In wav2feature_librosa.py and wav2feature_python_speech_features.py delta1 does not get initialized if  use_delta1 is true and use_delta2 is false.

(2) When preprocessing only libri-speech-100 a character.txt file does not get created. My workaround was that I preprocessed train_all but fixed the paths so only the ones from libri-speech-100 would get used.

**Comment by hirofumi0810** [comment]
@jesuistay , thank you.
I'll fix them in a few days.
After that, you will be able to create dataset only with 100h data (train-clean-100).

Please give me a moment.

**Comment by jesuistay** [comment]
Great to hear. After a couple of days with the project, I gotta commend you for a great piece of code overall. Well earned star.
