### ISSUE TITLE
location of make.sh

### ISSUE THREAD

**Issue by cuhkebook** [hirofumi0810/asr_preprocessing#3]
May I know where can find the make.sh in order to set the path?  Many thanks!

**Comment by hirofumi0810** [comment]
@cuhkebook 

make.sh was replaced with data_prep.sh.
I will update README.md.

Thank you.

**Comment by cuhkebook** [comment]
Thank a lot! I found it.
After update the data_prep.sh and run
./data_prep.sh
--------------
Traceback (most recent call last):
  File "make_config.py", line 15, in <module>
    from timit.path import Path
ImportError: No module named timit.path
----------------
Where can I find the timit.path in order to update it?  Thank you!

**Comment by hirofumi0810** [comment]
@cuhkebook 
I think it is due to python2.
Therefore, please add \_\_init\_\_.py.

**Comment by cuhkebook** [comment]
O...thank a lot!  It is solved as 
Add "__init__.py" into timit folder, which is an empty directory

Also need one more dependence:
pip install librosa
------------------------------------------
After, try again the ./data_prep.sh and get it:

===> Reading audio files...
0it [00:00, ?it/s]
===> Computing global mean & std over the training set...
Traceback (most recent call last):
  File "main.py", line 165, in <module>
    main()
  File "main.py", line 160, in main
    make_input()
  File "main.py", line 88, in make_input
    save_path=mkdir_join(input_save_path, 'train'))
  File "../timit/input_data.py", line 151, in read_audio
    feat_dim = input_data_list_male[0].shape[1]
IndexError: list index out of range
----------------------------------------
I figure out that my TIMIT corpus is in capital letter of "SX", "SI" and ".WAV", so the path.py cannot detect the filename.

**Comment by hirofumi0810** [comment]
@cuhkebook 
I think this is due to wrong path to TIMIT corpus.
Pleach check path.
